export const melodyDescriptions: any = {
    "Chord Progression": "A sequence of chords that aims to establish a tonality founded on a key. Common in nearly all genres, it's the backbone of a musical piece.",
    "Lead": "The main theme or melody that stands out in a mix. In various genres, the lead can be vocal, instrumental, or synth-based, guiding the song's melody.",
    "Sample-based": "Utilizes recordings from other pieces of music within a track. Predominantly found in hip-hop and electronic music, it can add depth or nostalgia.",
    "Arpeggio": "A broken chord where the notes are played in sequence rather than simultaneously. Common in classical and electronic music for creating texture.",
    "Bassline": "The low-end main melody that provides rhythmic and harmonic support. Key to genres like funk, disco, and electronic dance music.",
    "Hook": "A catchy musical phrase or motif meant to catch the listener's ear. Essential in pop and commercial music for memorability.",
    "Swing": "A rhythm that emphasizes the off-beat, common in jazz. Swing creates a 'groovy' feel, making the music feel more alive.",
    "Bebop Lines": "Complex and fast melodic lines typical of bebop jazz. They showcase instrumental virtuosity and improvisational skills.",
    "Modal": "Melodies based on modal scales rather than traditional major or minor scales, offering a different tonal palette, often heard in jazz.",
    "Riff": "A repeated chord progression or refrain in music. Riffs are integral to rock, metal, and blues to create memorable and driving melodies.",
    "Power Chords": "Chords that consist of the root note and the fifth. They are a staple in rock and metal for their full, powerful sound.",
    "Counterpoint": "The art of combining melodies that are harmonically interdependent yet independent in rhythm and contour, common in classical music.",
    "Orchestral Themes": "Melodic elements designed for orchestral settings, often thematic and used to convey specific moods or narratives in classical compositions.",
    "Off-beat Chords": "Chords played off the main beat, creating a syncopated rhythm. Essential to reggae and ska for their laid-back, groovy feel.",
    "Dub": "Involves remixing existing tracks to emphasize drums and bass. Common in electronic and reggae, dub can create a spacey, instrumental soundscape.",
    "Twangy Guitar": "A guitar sound with a sharp, ringing quality, characteristic of country music, often produced by a Telecaster.",
    "Banjo Rolls": "A rapid arpeggio played on the banjo, creating a lively, rolling sound. A signature of bluegrass and country music.",
    "Heavy Riffs": "Aggressive and heavy guitar riffs that are the foundation of metal music, characterized by their intensity and speed.",
    "Shredding Solos": "Fast, virtuosic, and highly technical guitar solos. Shredding is a hallmark of metal, showcasing the guitarist's skill.",
    "Smooth Vocals": "Vocals that are silky and expressive, often found in R&B, soul, and jazz, emphasizing emotional delivery and technique.",
    "Soulful Chords": "Chords that evoke deep emotional feelings, often used in R&B and soul music for their expressive quality.",
    "Synth Pads": "Sustained chord or tone generated by synthesizers, creating a backdrop for other musical elements. Common in ambient and lo-fi music.",
    "Synth Stabs": "Short, percussive synthesizer chords used to accentuate moments in a track. Widely used in techno and house for dynamic effect.",
    "Piano Chords": "The use of piano to create harmony and support the melody. Found across many genres, from classical to pop and jazz.",
};

export const drumDescriptions: any = {
    "Trap": "Defined by its use of synthesized drum sounds, 808 kick drums, rapid hi-hats, and snappy snares. Trap drums create a distinct, energetic rhythm ideal for hip-hop and electronic music.",
    "Boom Bap": "Features hard-hitting kicks and snares. Originating from East Coast hip-hop, it emphasizes a gritty, 'in the pocket' rhythm.",
    "Lo-fi": "Utilizes soft, laid-back beats with vinyl crackles and atmospheric noise, creating a warm, nostalgic sound ideal for relaxed listening.",
    "House": "Characterized by a four-on-the-floor beat, steady kick drums, and rhythmic hi-hats, house drums are foundational to dance music's upbeat feel.",
    "Techno": "Employs repetitive, synthesized drum patterns with a prominent four-on-the-floor kick, driving the genre's hypnotic, energetic essence.",
    "Breakbeat": "Diverges from the steady rhythm with varied, complex drum patterns, offering a dynamic, flexible foundation for electronic and hip-hop genres.",
    "Rock Beat": "Marked by a strong backbeat on the snare, complemented by bass drum hits, rock drums are the backbone of rock's driving, energetic sound.",
    "Hard Rock": "Amplifies the intensity with aggressive drumming, featuring loud, powerful drum beats that underscore the genre's raw energy.",
    "Double Bass": "Incorporates rapid, continuous beats on two bass drums, adding a thunderous, intense layer to metal and hard rock tracks.",
    "Blast Beats": "A technique involving extremely fast alternating hits on the snare and bass drums, creating an intense, aggressive texture common in extreme metal genres.",
    "Acoustic": "Refers to drums recorded or performed using traditional, non-electronic drum kits. Acoustic drums offer a natural, authentic sound widely used across genres.",
    "Brushes": "Drumsticks replaced with brushes to produce a softer, more subtle sound. Often used in jazz for playing lighter, more textured rhythms.",
    "Swing": "A style of drumming characterized by a swung note pattern, giving jazz its distinctive, lively rhythm that encourages movement.",
    "One Drop": "A reggae drum style where the emphasis is on the third beat in a 4/4 rhythm, creating a relaxed, laid-back feel.",
    "Steppers": "A type of reggae beat that features a bass drum hit on every beat, giving the music a steady, marching rhythm.",
    "Downtempo": "Features slow, relaxed beats that form the backdrop of lo-fi, ambient, and chillout music, emphasizing mood over tempo.",
    "Orchestral Percussion": "Encompasses a wide range of percussion instruments used in classical music, from timpani and snare drums to marimbas and cymbals, offering diverse textures.",
    "Classic Breaks": "Refers to breakbeats sampled from classic funk, soul, and R&B records, foundational to the rhythm in hip-hop and electronic music.",
};

export const genreDescriptions: any = {
    "Hip Hop": "A genre characterized by rhythmic music that accompanies rapping. Notable for its use of sampling, beatboxing, and DJing.",
    "Electronic": "Encompasses music created using electronic devices and technology. It spans across various styles, including house, techno, and EDM.",
    "Pop": "A broad genre of music that is accessible and appeals to a wide audience. It often features catchy melodies and hooks.",
    "Jazz": "Originated from African American communities, jazz is known for its swing and blue notes, complex chords, and improvisation.",
    "Rock": "Characterized by its use of electric guitars, drums, and strong rhythms. It has many subgenres, including punk, metal, and indie.",
    "Classical": "Rooted in Western art music traditions, classical music is known for its orchestral compositions, structured forms, and wide range of expressions.",
    "Reggae": "A music genre that originated in Jamaica, reggae is distinguished by its slow tempo, accentuated off-beat rhythms, and socially conscious lyrics.",
    "Blues": "Blues music is characterized by its use of the twelve-bar blues form, expressive lyrics, and signature guitar and harmonica sounds.",
    "Country": "Country music originates from the Southern United States and is known for its storytelling, simple chords, and twangy guitar sounds.",
    "Metal": "Heavy metal is known for its loud, aggressive sound, extended guitar solos, and emphatic beats. Themes often explore complex narratives.",
    "R&B": "R&B, or Rhythm and Blues, combines jazz, gospel, and blues influences, known for its soulful vocals and emotive lyrics.",
    "Lo-fi": "Lo-fi music emphasizes imperfections in recording and production, often resulting in a relaxed and nostalgic sound.",
    "Techno": "A form of electronic dance music characterized by a repetitive beat and synthesized rhythms, originating from Detroit.",
    "House": "Originating in Chicago, house music features repetitive 4/4 beats, rhythms mainly provided by drum machines, and soulful vocals.",
};

export const tempoRangeDescriptions: any = [
    { range: [40, 50], description: "Largo: Very slow and broad, conveying a solemn, grandiose feel, often used in classical music to evoke a sense of majesty or profundity." },
    { range: [51, 60], description: "Larghetto: Slower than Andante, this tempo offers a warm, graceful presence, often used in classical pieces for introspective sections." },
    { range: [61, 76], description: "Adagio: Slow with a gentle, lyrical quality, suitable for expressive, emotional parts in romantic and classical music." },
    { range: [77, 92], description: "Andante: A walking pace tempo that's versatile and common in many musical styles, providing a steady, balanced progression." },
    { range: [93, 108], description: "Moderato: A moderate pace that maintains a balanced flow, offering flexibility across various genres for a controlled energy." },
    { range: [109, 120], description: "Allegretto: Slightly slower than Allegro, providing a light, lively atmosphere often found in chamber music and symphonies." },
    { range: [121, 132], description: "Allegro: Fast, bright, and upbeat, suitable for lively compositions in classical, jazz, and pop music." },
    { range: [133, 144], description: "Vivace: A lively and fast tempo that brings energy and vitality to a piece, often used in faster, joyful music." },
    { range: [145, 160], description: "Presto: Very fast, introducing a rush of energy and intensity, suitable for virtuosic displays in concertos and solos." },
    { range: [161, 176], description: "Prestissimo: An extremely fast tempo that challenges the performer's speed, used in pieces requiring a high degree of technical proficiency." },
    { range: [177, 200], description: "Allegrissimo: The fastest tempo, pushing the boundaries of musical speed to create an exhilarating listening experience." },
];

export const keyDescriptions: any = {
    "C Major": "C Major is often associated with purity and clarity. Its lack of sharps and flats makes it a common choice for beginners.",
    "A Minor": "A Minor, the relative minor of C Major, often conveys feelings of sadness, melancholy, or introspection.",
    "G Major": "G Major is known for its warm and soothing qualities, making it popular in folk and classical music.",
    "E Minor": "E Minor carries a somber and often dramatic tone, frequently used in music to express emotional depth.",
    "D Major": "D Major is bright and triumphant, commonly used in baroque and classical music for its uplifting and energetic feel.",
    "B Minor": "B Minor tends to evoke a sense of solemnity and is often used to convey serious, reflective, or melancholic moods.",
};

export const getTempoDescription = (tempo: number): string => {
    const description = tempoRangeDescriptions.find((d: { range: number[]; }) => tempo >= d.range[0] && tempo <= d.range[1])?.description;
    return description || "Tempo outside standard ranges. Unique and unclassifiable!";
};  